# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: GINGO
subtitle: The Lightweight Scaffold of Gin Web Project for Golang, aims to be developer faster.
description: The Lightweight Scaffold of Gin Web Project for Golang, aims to be developer faster.
author: tangheng1995
author_url: https://github.com/tangheng1995
language: zh_CN
timezone: UTC
source_dir: pages

# URL
url: http://gingo.importpkg.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Start Guide
start: "go get -u github.com/tangheng1995/gingo"

# Common Configuration
# twitter: zhangjinzhu
github: tangheng1995/gingo
# disqus_shortname: gingo
# algolia:
#   en:
#     api_key: 442683d88a109de42c6xxxxxxxxxxxx
#     index_name: gingo
#google_tag_manager: GTM-WSNxxxxx

# Writing
new_post_name: :title.md # File name of new posts
external_link: true # Open external links in new tab
filename_case: 0
relative_link: false
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: '  '

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: navy  # based from hexo offical site

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# deploy:
#   type: git
#   repository: https://__GITHUB_TOKEN__@github.com/jinzhu/gorm.io.git
#   branch: gh-pages
