---
layout: raw
description: The Lightweight Scaffold of Gin Web Project for Golang, aims to be developer faster.
subtitle: The Lightweight Scaffold of Gin Web Project for Golang, aims to be developer faster.
comments: false
---

<div class="container page-not-found">
  <h1>404</h1>
  <p>File not found</p>

  <p>
    The site configured at this address does not contain the requested file.
  </p>
<div>
